version: '3.8'

services:
  php-apache-environment:
      container_name: php-apache
      build:
          context: ./php
          dockerfile: Dockerfile
      depends_on:
          - db
      volumes:
          - ./php/src:/var/www/html/
      ports:
          - "8001:80"
        
  # Database
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdb
      MYSQL_PASSWORD: password
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db


volumes:
  dbdata: